services:
  mysql-m:
    image: mysql:latest
    container_name: mysql-m
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_db
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-master/my.cnf:/etc/mysql/my.cnf
    networks:
      - mysql-net

  mysql-s1:
    image: mysql:latest
    container_name: mysql-s1
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - ./mysql-slave1/my.cnf:/etc/mysql/my.cnf
    depends_on:
      - mysql-m
    networks:
      - mysql-net

  mysql-s2:
    image: mysql:latest
    container_name: mysql-s2
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3308:3306"
    volumes:
      - ./mysql-slave2/my.cnf:/etc/mysql/my.cnf
    depends_on:
      - mysql-m
    networks:
      - mysql-net

networks:
  mysql-net:
    driver: bridge